spring:
  application:
    name: gwanghwamun
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.caffeine.gwanghwamun
  default-consumes-media-type: application/json
  default-produces-media-type: application/json